#!/usr/bin/env python3
"""bakefont - bake a monospace TTF into terminal-cell alpha bitmaps for
movy.VideoExport.

Each glyph is rendered into one terminal cell (e.g. 19x38 px) as 8-bit
antialiased coverage. VideoExport alpha-blends these over the cell background,
so text in an exported video looks like terminal text.

Point size is auto-fit: the largest size whose advance fits the cell width and
whose ascent+descent fits the cell height. Glyphs are centered horizontally in
the cell, baseline centered vertically (terminal placement).

    tools/bakefont.py FONT.ttf NAME CELL_W CELL_H OUT_DIR [--label "Font Name"]
                      [--license "SIL OFL 1.1"]

writes OUT_DIR/NAME.zig (metadata + codepoint table) and OUT_DIR/NAME.bin (the
alpha atlas, embedded with @embedFile), plus OUT_DIR/NAME.png, a preview sheet
(not needed at runtime - look at it after every bake).

Needs Python 3 + Pillow (>= 10.1). Codepoints the font does not have are
skipped; block elements (U+2580..259F) are drawn procedurally by VideoExport
and never baked.
"""

import argparse
import os
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFont

ASCII = list(range(32, 127))
EXTRA = (
    "·•…–—◉●○◆■□▲▼►◄★✓✗×÷±°©"
    "←→↑↓"
    "─│┌┐└┘├┤┬┴┼═║╔╗╚╝╠╣╦╩╬╭╮╯╰"
    "äöüÄÖÜßéèêàáçñ"
)


def fit(path, cw, ch):
    """Largest point size (0.25 steps) that fits the cell."""
    best = None
    pt = 4.0
    while pt < 200.0:
        f = ImageFont.truetype(path, pt)
        asc, desc = f.getmetrics()
        if f.getlength("M") > cw or asc + desc > ch:
            break
        best = pt
        pt += 0.25
    if best is None:
        sys.exit("font does not fit the cell at any size")
    return best


def render(font, cp, cw, ch):
    asc, desc = font.getmetrics()
    top = (ch - (asc + desc)) // 2
    x = (cw - font.getlength(chr(cp))) / 2.0
    img = Image.new("L", (cw, ch), 0)
    ImageDraw.Draw(img).text((x, top + asc), chr(cp), font=font, fill=255, anchor="ls")
    return img


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("font")
    ap.add_argument("name")
    ap.add_argument("cell_w", type=int)
    ap.add_argument("cell_h", type=int)
    ap.add_argument("out_dir")
    ap.add_argument("--label", default=None)
    ap.add_argument("--license", default="see the font's license")
    a = ap.parse_args()

    cw, ch = a.cell_w, a.cell_h
    pt = fit(a.font, cw, ch)
    font = ImageFont.truetype(a.font, pt)
    label = a.label or os.path.splitext(os.path.basename(a.font))[0]

    notdef = render(font, 0xFFFF, cw, ch)  # what a missing glyph looks like
    cps, cells = [], []
    for cp in sorted(set(ASCII + [ord(c) for c in EXTRA])):
        img = render(font, cp, cw, ch)
        if cp > 126 and ImageChops.difference(img, notdef).getbbox() is None:
            print(f"  skip U+{cp:04X} {chr(cp)!r}: not in the font")
            continue
        cps.append(cp)
        cells.append(img)

    os.makedirs(a.out_dir, exist_ok=True)
    base = os.path.join(a.out_dir, a.name)
    with open(base + ".bin", "wb") as fh:
        for img in cells:
            fh.write(img.tobytes())

    rows = []
    for i in range(0, len(cps), 12):
        rows.append("    " + ", ".join(f"0x{cp:04X}" for cp in cps[i:i + 12]) + ",")
    with open(base + ".zig", "w") as fh:
        fh.write(
            f"//! GENERATED by tools/bakefont.py (do not edit).\n"
            f"//! {label} @ {pt:g}pt -> {cw}x{ch} px alpha cells, {len(cps)} glyphs,\n"
            f"//! 8-bit coverage. Font license: {a.license}.\n"
            f"//! Regenerate: tools/bakefont.py <ttf> {a.name} {cw} {ch} {a.out_dir}\n\n"
            f'pub const label = "{label}";\n'
            f"pub const cell_w: usize = {cw};\n"
            f"pub const cell_h: usize = {ch};\n\n"
            f"/// sorted; glyph i's alpha is alpha[i * cell_w * cell_h ..][0 .. cell_w * cell_h]\n"
            f"pub const codepoints = [_]u21{{\n" + "\n".join(rows) + "\n};\n\n"
            f'pub const alpha = @embedFile("{a.name}.bin");\n'
        )

    # preview sheet: 16 per row, dark gray on black grid
    per = 16
    n_rows = (len(cells) + per - 1) // per
    sheet = Image.new("RGB", (per * (cw + 2) + 2, n_rows * (ch + 2) + 2), (40, 40, 60))
    for i, img in enumerate(cells):
        x = 2 + (i % per) * (cw + 2)
        y = 2 + (i // per) * (ch + 2)
        cell = Image.new("RGB", (cw, ch), (0, 0, 0))
        cell.paste((230, 240, 255), (0, 0), img)
        sheet.paste(cell, (x, y))
    sheet.save(base + ".png")
    print(f"{label}: {pt:g}pt, {len(cps)} glyphs -> {base}.zig / .bin / .png")


if __name__ == "__main__":
    main()
